package com.roger.redis.model.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

import java.io.Serial;
import java.io.Serializable;
import java.util.Objects;

/**
 * JPA entity representing a country, mapped to the {@code countries} table.
 *
 * <p>Implements {@link Serializable} to support Kryo serialization for Redis caching.
 * Equality and hashing are based solely on the ISO 3166-1 alpha-3 code ({@code cca3}),
 * which is the natural business key for a country.</p>
 *
 * @author Roger
 */
@Entity
@Table(name = "countries")
public class Country implements Serializable {

    @Serial
    private static final long serialVersionUID = 1L;

    /** Surrogate primary key, auto-generated by the database. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** ISO 3166-1 alpha-3 country code (e.g. "USA", "MEX", "GBR"). */
    @Column(unique = true, nullable = false)
    private String cca3;

    /** Common (short) name of the country. */
    @Column(nullable = false)
    private String commonName;

    /** Official (formal) name of the country. */
    private String officialName;

    /** Name of the capital city. */
    private String capital;

    /** Geographic region (e.g. "Americas", "Europe"). */
    private String region;

    /** Geographic subregion (e.g. "Northern America", "Western Europe"). */
    private String subregion;

    /** Total population. */
    private long population;

    /** Total area in square kilometres. */
    private double area;

    /** Latitude of the country centroid. */
    private double latitude;

    /** Longitude of the country centroid. */
    private double longitude;

    /** Latitude of the capital city. */
    private double capitalLat;

    /** Longitude of the capital city. */
    private double capitalLng;

    /** URL pointing to the PNG flag image. */
    private String flagUrl;

    /** URL pointing to the SVG flag image. */
    private String flagSvg;

    /**
     * No-arg constructor required by JPA.
     */
    protected Country() {
        // JPA requires a default constructor
    }

    /**
     * All-args constructor for programmatic creation.
     *
     * @param cca3         ISO 3166-1 alpha-3 code
     * @param commonName   common name
     * @param officialName official name
     * @param capital      capital city name
     * @param region       geographic region
     * @param subregion    geographic subregion
     * @param population   total population
     * @param area         total area (km²)
     * @param latitude     country centroid latitude
     * @param longitude    country centroid longitude
     * @param capitalLat   capital city latitude
     * @param capitalLng   capital city longitude
     * @param flagUrl      PNG flag URL
     * @param flagSvg      SVG flag URL
     */
    public Country(String cca3, String commonName, String officialName, String capital,
                   String region, String subregion, long population, double area,
                   double latitude, double longitude, double capitalLat, double capitalLng,
                   String flagUrl, String flagSvg) {
        this.cca3 = cca3;
        this.commonName = commonName;
        this.officialName = officialName;
        this.capital = capital;
        this.region = region;
        this.subregion = subregion;
        this.population = population;
        this.area = area;
        this.latitude = latitude;
        this.longitude = longitude;
        this.capitalLat = capitalLat;
        this.capitalLng = capitalLng;
        this.flagUrl = flagUrl;
        this.flagSvg = flagSvg;
    }

    // ──────────────────────────────────────────────
    // Getters and Setters
    // ──────────────────────────────────────────────

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getCca3() {
        return cca3;
    }

    public void setCca3(String cca3) {
        this.cca3 = cca3;
    }

    public String getCommonName() {
        return commonName;
    }

    public void setCommonName(String commonName) {
        this.commonName = commonName;
    }

    public String getOfficialName() {
        return officialName;
    }

    public void setOfficialName(String officialName) {
        this.officialName = officialName;
    }

    public String getCapital() {
        return capital;
    }

    public void setCapital(String capital) {
        this.capital = capital;
    }

    public String getRegion() {
        return region;
    }

    public void setRegion(String region) {
        this.region = region;
    }

    public String getSubregion() {
        return subregion;
    }

    public void setSubregion(String subregion) {
        this.subregion = subregion;
    }

    public long getPopulation() {
        return population;
    }

    public void setPopulation(long population) {
        this.population = population;
    }

    public double getArea() {
        return area;
    }

    public void setArea(double area) {
        this.area = area;
    }

    public double getLatitude() {
        return latitude;
    }

    public void setLatitude(double latitude) {
        this.latitude = latitude;
    }

    public double getLongitude() {
        return longitude;
    }

    public void setLongitude(double longitude) {
        this.longitude = longitude;
    }

    public double getCapitalLat() {
        return capitalLat;
    }

    public void setCapitalLat(double capitalLat) {
        this.capitalLat = capitalLat;
    }

    public double getCapitalLng() {
        return capitalLng;
    }

    public void setCapitalLng(double capitalLng) {
        this.capitalLng = capitalLng;
    }

    public String getFlagUrl() {
        return flagUrl;
    }

    public void setFlagUrl(String flagUrl) {
        this.flagUrl = flagUrl;
    }

    public String getFlagSvg() {
        return flagSvg;
    }

    public void setFlagSvg(String flagSvg) {
        this.flagSvg = flagSvg;
    }

    // ──────────────────────────────────────────────
    // equals, hashCode, toString — based on cca3
    // ──────────────────────────────────────────────

    /**
     * Two {@code Country} instances are equal if they share the same {@code cca3} code.
     */
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Country other)) return false;
        return Objects.equals(cca3, other.cca3);
    }

    /**
     * Hash code derived from the {@code cca3} business key.
     */
    @Override
    public int hashCode() {
        return Objects.hashCode(cca3);
    }

    /**
     * Returns a concise string representation including the country code and common name.
     */
    @Override
    public String toString() {
        return "Country[cca3=%s, commonName=%s, capital=%s, region=%s, population=%d]"
                .formatted(cca3, commonName, capital, region, population);
    }
}
